projects:
    - natgw:
        - host:
            vlan: 3196
            site: a
            alias: dns
            ipv4addr: [10.0.1.10/24, 10.0.1.11/24, 10.0.1.12/24]
            ipv4gw: 10.0.1.1
            ipv6addr: [2001::10/64, 2001::11/64]
            ipv6gw: 2010::1
            pings:
              - 10.0.1.1
              # - 10.0.10.1
              # - 10.0.11.1
              # - 10.0.12.1
              # - 10.0.13.1
              # - 2001::1
              # - 2011::1              
